#!/bin/sh

cur_dir=`pwd`
echo "PWD: $cur_dir"

# install vim74 & ctags & cscope
#tar jxf package/vim-7.4.tar.bz2 -C .
tar jxf package/vim-8.0.tar.bz2 -C .
tar zxf package/ctags-5.8.tar.gz -C .
tar zxf package/cscope-15.8a.tar.gz -C .
#tar zxf package/global-6.3.3.tar.gz -C .
tar zxf package/global-6.5.5.tar.gz -C .
tar jxf package/ccglue-release-0.6.0.tar.bz2 -C .
sudo apt-get install libncurses5-dev lua5.2 liblua5.2-dev
#sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev ruby-dev mercurial lua5.2 liblua5.2-dev

die() {
	cd $cur_dir
	sudo rm -rf $1
	echo "$1 install fail!" >&2
	exit 1
}

for package in vim80 ctags-5.8 cscope-15.8a ccglue-0.6.0 global-6.5.5
do
	echo $package
	cd $package
	echo "\n install $package ..."

	if [ $package = "vim80" ]; then
		./configure --prefix=/usr \
			--enable-cscope \
			--enable-multibyte \
			--enable-xim \
			--enable-fontset \
			--enable-gui=gtk2 \
			--enable-luainterp=yes \
			--enable-rubyinterp=yes \
			--enable-perlinterp \
			--enable-pythoninterp \
			--with-python-config-dir=/usr/lib/python2.7/config-i386-linux-gnu/ \
			--with-features=huge \
			--with-x \
			>/dev/null 2>&1
	else
		./configure --prefix=/usr/local >/dev/null 2>&1
	fi

	sudo make >/dev/null 2>&1; sudo make install >/dev/null 2>&1
	[ $? -ne 0 ] && die $package
	cd $cur_dir
	sudo rm -rf $package
	echo " install $package done ...\n"
done


# create .vim folder and copy vimrc
[ ! -e "$HOME/.vim" ] && mkdir -p ~/.vim/
[ ! -e "$HOME/.vim/.swap" ] && mkdir -p ~/.vim/.swap
[ ! -e "$HOME/.vim/.undodir" ] && mkdir -p ~/.vim/.undodir
cp -v vimrc ~/.vim/
cp -rf scripts ~/.vim/
cp -rf colors ~/.vim/

cd ~/.vim
ln -s scripts/tags tag
ln -s scripts/ktags ktags
echo "alias vi='vim'" >> ~/.bashrc
echo "alias e='vim'" >> ~/.bashrc
echo "alias g='gvim'" >> ~/.bashrc
echo "export PATH=~/.vim/:\$PATH" >> ~/.bashrc
echo "\n configure vimrc done ...\n"
