#!/bin/bash
global_version="global-6.6.4"
ctags_version="ctags-5.8"
cscope_version="cscope-15.8a"
ccglue_version="ccglue-0.6.0"

# trim space
trim() {
    str=""

    if [ $# -gt 0 ]; then
        str="$1"
    fi
    echo "$str" | sed -e 's/^[ \t\r\n]*//g' | sed -e 's/[ \t\r\n]*$//g'
}

# get system type, eg. ubuntu centos alpine
get_os_type() {
    #os=$(trim $(cat /etc/os-release 2>/dev/null | grep ^ID= | awk -F= '{print $2}'))
    os=$(trim $(awk -F= '/^ID=/{print $2}' /etc/os-release))

    if [ "$os" = "" ]; then
        os=$(trim $(lsb_release -i 2>/dev/null | awk -F: '{print $2}'))
    fi

    if [ ! "$os" = "" ]; then
        os=$(echo $os | tr '[A-Z]' '[a-z]')
    fi

    echo $os
}

install_depend() {
    case "$os" in
    ubuntu)
        #sudo apt install git python-dev ruby-dev libncurses5-dev lua5.2 liblua5.2-dev
        sudo apt install cscope universal-ctags global
        ;;
    centos)
        yum install git python-dev ruby-dev libncurses5-dev lua5.2 liblua5.2-dev
        ;;
    *)
        echo unknow os $OS, exit!
        return
        ;;
    esac
}

make_install_vim() {
    git clone https://github.com/vim/vim.git
    cd $current_dir/vim/
    echo $PWD
    echo "##### install vim #####"

    ./configure --prefix=/usr \
        --enable-cscope \
        --enable-multibyte \
        --enable-xim \
        --enable-fontset \
        --enable-gui=gtk2 \
        --enable-luainterp=yes \
        --enable-rubyinterp=yes \
        --enable-perlinterp \
        --enable-pythoninterp \
        --with-python-config-dir=/usr/lib/python2.7/config-i386-linux-gnu/ \
        --with-features=huge \
        --with-x \
        >/dev/null 2>&1

    make >/dev/null 2>&1;
    sudo make install >/dev/null 2>&1
    [ $? -ne 0 ] && echo "make vim abort, leave $PWD" && exit 1
    cd $current_dir && rm -rf vim
    echo "##### install vim done #####"
}

make_install_plug() {
	wget https://ftp.gnu.org/pub/gnu/global/$global_version.tar.gz
	tar zxf global*.tar.gz -C .
	tar zxf packages/ctags*.tar.gz -C .
	tar zxf packages/cscope*.tar.gz -C .
	tar jxf packages/ccglue*.tar.bz2 -C .

	for package in $global_version $ctags_version $cscope_version $ccglue_version
	do
		cd $current_dir/$package
		echo ""
		echo "##### install $package #####"

		./configure --prefix=/usr/local >/dev/null 2>&1

		make >/dev/null 2>&1
		sudo make install >/dev/null 2>&1
		[ $? -ne 0 ] && echo "make $package abort, leave $PWD" && exit 1
		cd $current_dir && rm -rf $package*
		echo "##### install $package done #####"
	done
}

macos_install() {
	brew install vim
	brew install ctags
}

vim_config() {
	# create .vim folder and copy vimrc
	[ ! -e "$HOME/.vim" ] && mkdir -p ~/.vim/
	[ ! -e "$HOME/.vim/.swap" ] && mkdir -p ~/.vim/.swap
	[ ! -e "$HOME/.vim/.undodir" ] && mkdir -p ~/.vim/.undodir
	cp -v $current_dir/vimrc ~/.vim/
	cp -rvf $current_dir/scripts ~/.vim/

	if [ -f $HOME/.bashrc ]; then
		echo "" >> $HOME/.bashrc
		echo "# configure for vim" >> $HOME/.bashrc
		echo "alias vi='vim'" >> $HOME/.bashrc
		echo "export PATH=~/.vim/scripts/:\$PATH" >> $HOME/.bashrc
	elif [ -f $HOME/.zshrc ]; then
		echo "" >> $HOME/.zshrc
		echo "# configure for vim" >> $HOME/.zshrc
		echo "alias vi='vim'" >> $HOME/.zshrc
		echo "export PATH=~/.vim/scripts/:\$PATH" >> $HOME/.zshrc
	fi
	echo "----- Configure vimrc done. -----"
}

current_dir=`pwd`
echo "The current installation directory is $current_dir"

get_os_type
vim_config

if [ "$os" = "ubuntu" ]; then
    install_depend
    #make_install_vim  #not install by default, use system vim
    #make_install_plug #not install by default, installed through apt at install_depend
else
    macos_install
fi

exit 0

