#!/bin/bash

function file_list() {
	if [ -f .vimproj/files.list ]; then
		echo "remove files.list"
		rm -vf .vimproj/files.list
		touch .vimproj/files.list
	fi

	echo "create files.list"
	echo -n "search dirs: "
	echo -n -e '\e[;32m'
	echo $DIRS
	echo -n -e '\e[0m'

	for dir in $DIRS; do
		find $PWD/$dir -type f -name "*.h" \
			-o -type f -name "*.c" \
			-o -type f -name "*.cc" \
			-o -type f -name "*.cpp" \
			-o -type f -name "*.java" \
			>> .vimproj/files.list
	done

	find $PWD -maxdepth 1 -type f -name "*.h" \
		-o -type f -name "*.c" \
		-o -type f -name "*.cc" \
		-o -type f -name "*.cpp" \
		-o -type f -name "*.java" \
		>> .vimproj/files.list

	echo "create files.list successful"
}

function create_cscope() {

	new=y

	if [ -f .vimproj/cscope.out ]; then
		read -p "cscope tags already exist!  Re-create? [yes/no] " new
	fi

	if [[ "$new" == "y" ]] || [[ "$new" == "yes" ]]; then
		if [ -d arch ] && [ -f ~/.vim/ktags ]; then
			echo "create ktags cscope ..."
			time ktags cscope
		else
			file_list
			echo "create cscope.out ..."
			time cscope -bkq -i .vimproj/files.list
		fi

		mv -v cscope* .vimproj
		echo -e "\e[;32mdone. \e[0m"
	else
		return 0
	fi

	return 0
}

function create_tags() {

	new=y

	if [ -f .tags ]; then
		read -p "tags already exists! Re-create? [yes/no] " new
	fi

	if [[ "$new" == "y" ]] || [[ "$new" == "yes" ]]; then
		if [ -d arch ] && [ -f ~/.vim/ktags ]; then
			echo "create ktags tags ..."
			time ktags tags
		else
			if [ ! -s .vimproj/files.list ]; then
				file_list
			fi

			echo "create tags ..."
			time ctags -L .vimproj/files.list --c-kinds=+p --c++-kinds=+p --java-kinds=+l --fields=+lS --links=no -f .tags
		fi

		echo -e "\e[;32mdone. \e[0m"
	fi

	return 0
}

function create_gtags() {

	new=y

	if [ -f .GTAGS ]; then
		read -p "gtags already exists! Re-create? [yes/no] " new
	fi

	if [[ "$new" == "y" ]] || [[ "$new" == "yes" ]]; then
		if [ ! -s .vimproj/files.list ]; then
			file_list
		fi

		echo "create gtags ..."
		time gtags -f .vimproj/files.list

		echo -e "\e[;32mdone. \e[0m"
	fi

	return 0
}

function create_ftags() {

	new=y

	if [ -f .filenametags ]; then
		read -p "filename tags already exist! Re-create? [yes/no] " new
	fi

	if [[ "$new" == "y" ]] || [[ "$new" == "yes" ]]; then
		echo "create filenametags ..."

        time \
		(echo "!_TAG_FILE_SORTED        2       /2=foldcase/";
        (find $PWD -not -regex '.*\.\(jar\|gif\|jpg\|class\|exe\|dll\|pdd\|sw[op]\|xls\|doc\|pdf\|zip\|tar\|ico\|ear\|war\|dat\|png\|gif\|html\)' -type f -printf "%f\t%p\t1\n" | \
                sort -f )) > ./.filenametags

		echo -e "\e[;32mdone. \e[0m"
	fi

	return 0
}

function create_ccglue() {
	ccglue -S .vimproj/cscope.out -o .vimproj/cctree.out
}

function create_dir() {
	if [ ! -d .vimproj ]; then
		mkdir -v .vimproj
	fi
}

function remove_file() {
	rm -rvf .vimproj

	if [ -f ncscope.out ]; then
		rm -vf ncscope.out
	fi

	if [ -f .tags ]; then
		rm -vf  .tags
	fi

	if [ -f .GTAGS ]; then
		rm -vf  .GTAGS .GRTAGS .GPATH
	fi

	if [ -f .filenametags ]; then
		rm -vf  .filenametags
	fi
}

function tag_status() {
	if [ -f .vimproj/cscope.out ]; then
		echo -e 'check cscope index          [\e[;32m ok \e[0m]'
	else
		echo -e 'check cscope index          [\e[;31mfail\e[0m]'
	fi

	if [ -f .tags ]; then
		echo -e 'check ctags  index          [\e[;32m ok \e[0m]'
	else
		echo -e 'check ctags  index          [\e[;31mfail\e[0m]'
	fi

	if [ -f .GTAGS ]; then
		echo -e 'check gtags  index          [\e[;32m ok \e[0m]'
	else
		echo -e 'check gtags  index          [\e[;31mfail\e[0m]'
	fi

	if [ -f .filenametags ]; then
		echo -e 'check lookup index          [\e[;32m ok \e[0m]'
	else
		echo -e 'check lookup index          [\e[;31mfail\e[0m]'
	fi

	if [ -f .vimproj/cctree.out ]; then
		echo -e 'check cctree index          [\e[;32m ok \e[0m]'
	else
		echo -e 'check cctree index          [\e[;31mfail\e[0m]'
	fi
}

function file_size() {
	echo "----------------------------------"

	du -shc ".tags" ".vimproj/" ".filenametags" ".GTAGS"

	#oujf1
	str=`du -skc ".tags" ".vimproj/" ".filenametags" ".GTAGS"`
	size=`echo $str | awk '{split($0,str," ");printf "%.2f\n",str[7]/1024}'`
	echo -e "total size \e[;31m$size\e[0mM"

	echo "----------------------------------"
}

function error() {
	echo "Usage: tag [OPTION]..."
	echo "Try tag --help' for more information."
}

function usage() {
	echo "usage: tag  <command>"
	echo "       n | new     new create cscope and ctags index."
	echo "       a | all     recreate cscope and ctags index."
	echo "       cs| cscope  create cscope index."
	echo "       cc| ccglue  create ccglue index."
	echo "       g | gtags   create gtags index."
	echo "       t | tag     create ctags index."
	echo "       f | ftag    filenametags"
	echo "       c | clean   remove all tags files"
	echo "       s | status  check tag status"
	return 0
}

function version() {
	echo "tag v0.5 by oujf1 2011-11-11 11:11:11"
	echo "Addresses: <oujf@outlook.com>"
	exit 0
}

if [ -n "$1" ]; then
	[ "$1" = "-h" ] && usage
	[ "$1" = "-v" ] && version
	[ "$1" = "--help" ] && usage
fi

case $2 in
	"s" | "sub")
		DIRS=`ls -F | grep "/$"`
		;;
	"m" | "mtk")
		DIRS="frameworks kernel system mediatek packages bionic external libcore"
		;;
	*)
		DIRS=`ls -F | grep "/$"`
		;;
esac

case $1 in
	"n" | "new")
		remove_file
		create_dir
		create_gtags
		#create_cscope
		#create_tags
        create_ftags
		file_size
		;;
	"a" | "all")
		create_dir
		create_gtags
		#create_cscope
		#create_tags
        create_ftags
		;;
	"g" | "gtags")
		create_dir
		create_gtags
		;;
	"cs" | "cscope")
		create_dir
		create_cscope
		;;
	"cc" | "ccglue")
		create_ccglue
		;;
	"t" | "tag" | "tags")
		create_dir
		create_tags
		;;
	"f" | "ftag")
		create_dir
		create_ftags
		;;
	"c" | "clean")
		remove_file
		;;
	"s" | "status")
		tag_status
		file_size
		;;
	"")
		error
		;;
esac
